apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/instance: webapp
  name: dashborad-ingress
  namespace: kubernetes-dashboard
spec:
  rules:
    - host: dashboard.com
      http:
        paths:
          - backend:
              service:
                name: taskapp-service
                port:
                  number: 8080
            path: /taskapp
            pathType: Prefix