apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: taskapp
spec:
  serviceName: "mongo"
  replicas: 3
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: "mongo:4.2.16"
        command:
          - "mongodb"
          - "--replSet"
          - rs0
          - "--smallfiles"
          - "--noprealloc"
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: taskapp-secrets
              key: db_user
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: taskapp-secrets
              key: db_password
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb1-data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongodb1-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
