apiVersion: v1
kind: Service
metadata:
  name: taskapp-service
  labels:
    app: taskapp
    env: dev
  namespace: taskapp
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8081
  selector:
    app: myapp
  type: NodePort
