apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-data
  labels:
    type: mongo
spec:
  storageClassName: "standard"
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/varshan/Daily/d1"