apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app.kubernetes.io/instance: webapp
  name: mongodb-pv
  namespace: taskapp
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /mydata
  storageClassName: ''

---
apiVersion : v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data
  namespace: taskapp
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
