apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapp
    app.kubernetes.io/instance: webapp
  name: myapp
  namespace: taskapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - env:
            - name: MYAPP_DB_HOST
              value: MONGODB_SERVICE_HOST
            - name: MYAPP_DB_PORT
              value: '27017'
            - name: MYAPP_DB_USER
              valueFrom:
                secretKeyRef:
                  key: db_user
                  name: taskapp-secrets
            - name: MYAPP_DB_PASS
              valueFrom:
                secretKeyRef:
                  key: db_password
                  name: taskapp-secrets
          image: 'mytaskapp:v1'
          name: myapp
          ports:
            - containerPort: 8080