apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
namespace: taskapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: mytaskapp:latest
        ports:
        - containerPort: 8080
        env:
        - name: MYAPP_DB_HOST
          value: MONGODB_SERVICE_HOST
        - name: MYAPP_DB_PORT
          value: "27017"
        - name: MYAPP_DB_USER
          valueFrom:
            secretKeyRef:
              name: taskapp-secrets
              key: db_user
        - name: MYAPP_DB_PASS
          valueFrom:
            secretKeyRef:
              name: taskapp-secrets
              key: db_password