apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapp
    app.kubernetes.io/instance: webapp
  name: myapp
  namespace: taskapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        env:
        - name: MYAPP_DB_HOST
          value: "192.168.1.8"
        - name: MYAPP_DB_PORT
          value: '27017'
        - name: MYAPP_DB_USER
          #valueFrom:
          # secretKeyRef:
          #   key: db_user
          #   name: taskapp-secrets
          value: ""
        - name: MYAPP_DB_PASS
          #valueFrom:
          # secretKeyRef:
          #   key: db_password
          #   name: taskapp-secrets
          value: ""
        image: 'docker.io/sainadh086/mytaskapp:v7'
        name: myapp
        ports:
          - containerPort: 8080
