apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapp
    app.kubernetes.io/instance: webapp
  name: myapp
  namespace: taskapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        env:
        - name: MYAPP_DB_HOST
          value: mongo_SERVICE_HOST
        - name: MYAPP_DB_PORT
          value: '27017'
        - name: MYAPP_DB_USER
          valueFrom:
            secretKeyRef:
              key: db_user
              name: taskapp-secrets
        - name: MYAPP_DB_PASS
          valueFrom:
            secretKeyRef:
              key: db_password
              name: taskapp-secrets
        image: 'docker.io/sainadh086/mytaskapp:v7'
        livenessProbe:
          exec:
            command: ["/bin/sh", "-c", "sleep 15"]
          initialDelaySeconds: 10
          periodSeconds: 5
        ports:
          - containerPort: 8080
