name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: build a docker image
        run: docker build -t devapp:v1 .

      - name: run the image
        shell: bash
        env:
          user_name: ${{ secrets.DOCKER_USER_NAME }}
          user_password: ${{ secrets.DOCKER_USER_PASSWORD }}
          host: ${{ secrets.HOST }}
        run: |
          export ver=${{ github.run_number }}
          echo $ver
          docker login -u $user_name -p $user_password
          docker tag devapp:v1 sainadh086/mytaskapp:v$ver
          echo "Success"
          echo "Testing"
          echo "Started testing the docker app"
          docker run -p 8080:8080 -e MYAPP_DB_HOST=$host -e MYAPP_BD_PORT=27017 -e MYAPP_DB_USER="" -e MYAPP_DB_PASSWORD="" sainadh086/mytaskapp:v$ver
          echo "Just ran the docker app"
      - name: run the tests
        run: |
          export status=$(curl -i http://localhost:8080/ | awk 'NR == 1' | awk '{print $2}')
          if [ $status == 200 ]; then echo "Success"; else echo "failed"; fi
          echo "Completed testing"
      - name: Push the docker image to the repository if testing is successful
        run: |          
          if [$status == 200 ]; then docker push sainadh086/mytaskapp:v$ver; else echo "Docker push cancelled"; fi
